from collections.abc import Callable, Hashable, Iterator, Mapping, Sequence
from typing import Any, ClassVar, Generic, TypeAlias, TypeVar, final, overload

import numpy as np
import numpy.typing as npt
from autd3_core import Angle, Device, Geometry, Intensity, Length, Phase, Velocity

_K = TypeVar("_K", bound=Hashable)
_Vec3: TypeAlias = Sequence[float] | npt.NDArray[np.floating[Any]]

@final
class DevicePhaseView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Phase: ...
    def __iter__(self) -> Iterator[Phase]: ...
    def __setitem__(self, index: int, value: Phase | int) -> None: ...

@final
class PhaseBuffer:
    def __new__(cls, num_devices: int) -> PhaseBuffer: ...
    @staticmethod
    def from_array(values: npt.NDArray[np.uint8] | Sequence[Sequence[Phase | int]]) -> PhaseBuffer: ...
    def copy_from(self, values: npt.NDArray[np.uint8]) -> None: ...
    def to_numpy(self) -> npt.NDArray[np.uint8]: ...
    def num_devices(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> DevicePhaseView: ...
    def __iter__(self) -> Iterator[DevicePhaseView]: ...
    def _capsule(self) -> object: ...

@final
class DeviceIntensityView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Intensity: ...
    def __iter__(self) -> Iterator[Intensity]: ...
    def __setitem__(self, index: int, value: Intensity | int) -> None: ...

@final
class IntensityBuffer:
    def __new__(cls, num_devices: int) -> IntensityBuffer: ...
    @staticmethod
    def from_array(values: npt.NDArray[np.uint8] | Sequence[Sequence[Intensity | int]]) -> IntensityBuffer: ...
    def copy_from(self, values: npt.NDArray[np.uint8]) -> None: ...
    def to_numpy(self) -> npt.NDArray[np.uint8]: ...
    def num_devices(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> DeviceIntensityView: ...
    def __iter__(self) -> Iterator[DeviceIntensityView]: ...
    def _capsule(self) -> object: ...

@final
class TransducerMask:
    AllEnabled: ClassVar[TransducerMask]
    @staticmethod
    def masked(mask: Sequence[Sequence[bool]]) -> TransducerMask: ...
    def validate(self, geometry: Geometry) -> None: ...
    def is_enabled(self, device: int, transducer: int) -> bool: ...
    def num_enabled(self, geometry: Geometry) -> int: ...

@final
class TransducerGroups(Generic[_K]):
    def __new__(cls, geometry: Geometry, key: Callable[[Device, int], _K]) -> TransducerGroups[_K]: ...
    def keys(self) -> list[_K]: ...
    def key(self, device: int, transducer: int) -> _K: ...
    def index(self, device: int, transducer: int) -> int: ...
    def indices(self, device: int) -> list[int]: ...
    def num_devices(self) -> int: ...
    def num_transducers(self, device: int) -> int: ...
    def num_transducers_in(self, key: _K) -> int: ...
    def masks(self) -> list[tuple[_K, TransducerMask]]: ...
    def mask(self, key: _K) -> TransducerMask: ...

@final
class LaguerreGaussianOption:
    def __new__(cls, p: int, l: int, waist: Length) -> LaguerreGaussianOption: ...
    @property
    def p(self) -> int: ...
    @property
    def l(self) -> int: ...
    @property
    def waist(self) -> Length: ...

@final
class HermiteGaussianOption:
    def __new__(cls, m: int, n: int, waist: Length) -> HermiteGaussianOption: ...
    @property
    def m(self) -> int: ...
    @property
    def n(self) -> int: ...
    @property
    def waist(self) -> Length: ...

def wavelength(sound_speed: Velocity) -> Length: ...
def focus(geometry: Geometry, target: _Vec3, wavelength: Length, dst: PhaseBuffer) -> None: ...
def plane(geometry: Geometry, direction: _Vec3, wavelength: Length, dst: PhaseBuffer) -> None: ...
def bessel(
    geometry: Geometry,
    apex: _Vec3,
    direction: _Vec3,
    theta: Angle,
    wavelength: Length,
    dst: PhaseBuffer,
) -> None: ...
def laguerre_gaussian_phase(
    geometry: Geometry,
    target: _Vec3,
    axis: _Vec3,
    option: LaguerreGaussianOption,
    wavelength: Length,
    dst: PhaseBuffer,
) -> None: ...
def laguerre_gaussian_intensity(
    geometry: Geometry,
    target: _Vec3,
    axis: _Vec3,
    option: LaguerreGaussianOption,
    wavelength: Length,
    dst: IntensityBuffer,
) -> None: ...
def hermite_gaussian_phase(
    geometry: Geometry,
    target: _Vec3,
    axis: _Vec3,
    x_dir: _Vec3,
    option: HermiteGaussianOption,
    wavelength: Length,
    dst: PhaseBuffer,
) -> None: ...
def hermite_gaussian_intensity(
    geometry: Geometry,
    target: _Vec3,
    axis: _Vec3,
    x_dir: _Vec3,
    option: HermiteGaussianOption,
    wavelength: Length,
    dst: IntensityBuffer,
) -> None: ...
def focus_device(device: Device, target: _Vec3, wavelength: Length, dst: npt.NDArray[np.uint8]) -> None: ...
def focus_transducer(position: _Vec3, target: _Vec3, wavelength: Length) -> Phase: ...
def plane_device(device: Device, direction: _Vec3, wavelength: Length, dst: npt.NDArray[np.uint8]) -> None: ...
def plane_transducer(position: _Vec3, direction: _Vec3, wavelength: Length) -> Phase: ...
def bessel_device(
    device: Device,
    apex: _Vec3,
    direction: _Vec3,
    theta: Angle,
    wavelength: Length,
    dst: npt.NDArray[np.uint8],
) -> None: ...
def bessel_transducer(
    position: _Vec3,
    apex: _Vec3,
    direction: _Vec3,
    theta: Angle,
    wavelength: Length,
) -> Phase: ...
def laguerre_gaussian_phase_device(
    device: Device,
    target: _Vec3,
    axis: _Vec3,
    option: LaguerreGaussianOption,
    wavelength: Length,
    dst: npt.NDArray[np.uint8],
) -> None: ...
def laguerre_gaussian_phase_transducer(
    position: _Vec3,
    target: _Vec3,
    axis: _Vec3,
    option: LaguerreGaussianOption,
    wavelength: Length,
) -> Phase: ...
def laguerre_gaussian_intensity_device(
    device: Device,
    target: _Vec3,
    axis: _Vec3,
    option: LaguerreGaussianOption,
    wavelength: Length,
    dst: npt.NDArray[np.uint8],
) -> None: ...
def hermite_gaussian_phase_device(
    device: Device,
    target: _Vec3,
    axis: _Vec3,
    x_dir: _Vec3,
    option: HermiteGaussianOption,
    wavelength: Length,
    dst: npt.NDArray[np.uint8],
) -> None: ...
def hermite_gaussian_phase_transducer(
    position: _Vec3,
    target: _Vec3,
    axis: _Vec3,
    x_dir: _Vec3,
    option: HermiteGaussianOption,
    wavelength: Length,
) -> Phase: ...
def hermite_gaussian_intensity_device(
    device: Device,
    target: _Vec3,
    axis: _Vec3,
    x_dir: _Vec3,
    option: HermiteGaussianOption,
    wavelength: Length,
    dst: npt.NDArray[np.uint8],
) -> None: ...
def set_intensity(intensity: Intensity | int, dst: IntensityBuffer) -> None: ...
def set_phase(phase: Phase | int, dst: PhaseBuffer) -> None: ...
def add_phase(phase: Phase | int, dst: PhaseBuffer) -> None: ...
@overload
def group(
    geometry: Geometry,
    groups: TransducerGroups[_K],
    sources: Mapping[_K, PhaseBuffer],
    dst: PhaseBuffer,
) -> None: ...
@overload
def group(
    geometry: Geometry,
    groups: TransducerGroups[_K],
    sources: Mapping[_K, IntensityBuffer],
    dst: IntensityBuffer,
) -> None: ...
def group_device(
    device: Device,
    groups: TransducerGroups[_K],
    sources: Mapping[_K, PhaseBuffer] | Mapping[_K, IntensityBuffer],
    dst: npt.NDArray[np.uint8],
) -> None: ...
def group_compute(
    geometry: Geometry,
    groups: TransducerGroups[_K],
    compute: Callable[[_K, TransducerMask, PhaseBuffer, IntensityBuffer], object],
    phases: PhaseBuffer,
    intensities: IntensityBuffer,
) -> None: ...
