[package]
name = "autd3-rs-pattern"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Emission-pattern computation utilities for autd3-rs (focus, bessel beam, etc.)."
readme = "README.md"
keywords = ["autd3", "haptics"]
categories = ["science"]

[lib]
bench = false

[dependencies]
autd3-rs-core.workspace = true

[dev-dependencies]
approx.workspace = true
criterion = { version = "0.8.2", default-features = false }

[[bench]]
name = "layout"
harness = false

[lints]
workspace = true
