set_input_delay -clock cpu_bsc_75M -max 11.000 [get_ports {CPU_CS1_N CPU_RDWR CPU_ADDR[*] CPU_DATA[*]}]
set_input_delay -clock cpu_bsc_75M -min 0.000 [get_ports {CPU_CS1_N CPU_RDWR CPU_ADDR[*] CPU_DATA[*]}]
set_input_delay -clock cpu_bsc_75M -clock_fall -max 11.000 [get_ports {CPU_WE0_N CPU_RD_N}]
set_input_delay -clock cpu_bsc_75M -clock_fall -min 0.000 [get_ports {CPU_WE0_N CPU_RD_N}]
set_multicycle_path -hold 1 -from [get_ports {CPU_CS1_N CPU_ADDR[*] CPU_DATA[*]}]
set_multicycle_path -setup 2 -from [get_ports CPU_WE0_N]
set_multicycle_path -hold 1 -from [get_ports CPU_WE0_N]
set_output_delay -clock cpu_bsc_75M -clock_fall -max 5.000 [get_ports CPU_DATA[*]]
set_output_delay -clock cpu_bsc_75M -clock_fall -min 0.000 [get_ports CPU_DATA[*]]
set_multicycle_path -setup 2 -to [get_ports CPU_DATA[*]]
set_multicycle_path -hold 1 -to [get_ports CPU_DATA[*]]
set_multicycle_path -setup 3 -from [get_ports CPU_RD_N] -to [get_ports CPU_DATA[*]]
set_multicycle_path -hold 2 -from [get_ports CPU_RD_N] -to [get_ports CPU_DATA[*]]
set_multicycle_path -setup 5 -from [get_ports {CPU_CS1_N CPU_RDWR}] -to [get_ports CPU_DATA[*]]
set_multicycle_path -hold 4 -from [get_ports {CPU_CS1_N CPU_RDWR}] -to [get_ports CPU_DATA[*]]
set_property IOBDELAY NONE [get_nets -of_objects [get_ports {CPU_CS1_N CPU_WE0_N CPU_ADDR[*] CPU_DATA[*]}]]

set_input_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -min 0.500 [get_ports CAT_SYNC0]
set_input_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -max 1.500 [get_ports CAT_SYNC0]
set_input_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -min 0.500 [get_ports RESET_N]
set_input_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -max 1.500 [get_ports RESET_N]
set_false_path -from [get_ports THERMO]
set_input_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -min 0.500 [get_ports GPIO_IN*]
set_input_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -max 1.500 [get_ports GPIO_IN*]
set_output_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -min 0.500 [get_ports FORCE_FAN*]
set_output_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -max 1.500 [get_ports FORCE_FAN*]
set_output_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -min 0.500 [get_ports XDCR_OUT*]
set_output_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -max 1.500 [get_ports XDCR_OUT*]
set_output_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -min 0.500 [get_ports GPIO_OUT*]
set_output_delay -clock [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -max 1.500 [get_ports GPIO_OUT*]
set_max_delay -datapath_only -from [get_ports CAT_SYNC0] -to [get_ports GPIO_OUT*] 20.000

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 0x001D0000 [current_design]
set_property BITSTREAM.CONFIG.USR_ACCESS 0x55504454 [current_design]

set_false_path -to [get_ports {FLASH_CS_N FLASH_MOSI FLASH_WP_N FLASH_HOLD_N}]
set_false_path -from [get_ports FLASH_MISO]
set_max_delay -datapath_only -from [get_clocks cpu_bsc_75M] -to [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] 10.000
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins main/clk_wiz/clk_out1]] -to [get_clocks cpu_bsc_75M] 10.000
