from collections.abc import Iterator, Sequence
from typing import final

import numpy as np
import numpy.typing as npt
from autd3_core import Angle, Freq, Nearest, SamplingConfig

@final
class SineOption:
    def __new__(
        cls,
        amplitude: int = 0xFF,
        offset: int = 0x80,
        phase: Angle = ...,
        clamp: bool = False,
        sampling_config: SamplingConfig = ...,
    ) -> SineOption: ...
    @property
    def amplitude(self) -> int: ...
    @property
    def offset(self) -> int: ...
    @property
    def phase(self) -> Angle: ...
    @property
    def clamp(self) -> bool: ...
    @property
    def sampling_config(self) -> SamplingConfig: ...
    def __eq__(self, other: object) -> bool: ...

@final
class SquareOption:
    def __new__(
        cls,
        low: int = 0x00,
        high: int = 0xFF,
        duty: float = 0.5,
        sampling_config: SamplingConfig = ...,
    ) -> SquareOption: ...
    @property
    def low(self) -> int: ...
    @property
    def high(self) -> int: ...
    @property
    def duty(self) -> float: ...
    @property
    def sampling_config(self) -> SamplingConfig: ...
    def __eq__(self, other: object) -> bool: ...

@final
class FourierOption:
    def __new__(
        cls,
        scale_factor: float | None = None,
        clamp: bool = False,
        offset: int = 0x00,
    ) -> FourierOption: ...
    @property
    def scale_factor(self) -> float | None: ...
    @property
    def clamp(self) -> bool: ...
    @property
    def offset(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class SineComponent:
    def __new__(cls, freq: Freq | Nearest, option: SineOption) -> SineComponent: ...
    @property
    def freq(self) -> Freq | Nearest: ...
    @property
    def option(self) -> SineOption: ...
    def __eq__(self, other: object) -> bool: ...

@final
class ModulationBuffer:
    def __new__(cls, length: int) -> ModulationBuffer: ...
    @staticmethod
    def from_bytes(data: bytes | Sequence[int]) -> ModulationBuffer: ...
    @staticmethod
    def from_array(values: npt.NDArray[np.uint8] | bytes | Sequence[int]) -> ModulationBuffer: ...
    def copy_from(self, values: npt.NDArray[np.uint8]) -> None: ...
    def to_numpy(self) -> npt.NDArray[np.uint8]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def _capsule(self) -> object: ...

def modulation_buffer() -> ModulationBuffer: ...
def sine(freq: Freq | Nearest, option: SineOption, dst: ModulationBuffer) -> None: ...
def square(freq: Freq | Nearest, option: SquareOption, dst: ModulationBuffer) -> None: ...
def constant(amplitude: int, dst: ModulationBuffer) -> None: ...
def fourier(components: Sequence[SineComponent], option: FourierOption, dst: ModulationBuffer) -> None: ...
def radiation_pressure(src: ModulationBuffer, dst: ModulationBuffer) -> None: ...
def radiation_pressure_inplace(buffer: ModulationBuffer) -> None: ...
def samples_per_period(divider: int, freq: Freq) -> int | None: ...
