[workspace]
resolver = "3"
members = [
    "crates/autd3-rs",
    "crates/autd3-rs-core",
    "crates/autd3-rs-firmware-emulator",
    "crates/autd3-rs-pattern",
    "crates/autd3-rs-pattern-holo",
    "crates/autd3-rs-link-echocat",
    "crates/autd3-rs-link-nop",
    "crates/autd3-rs-link-remote",
    "crates/autd3-rs-link-twincat",
    "crates/autd3-rs-modulation",
    "firmware/cpu/wire",
    "firmware/cpu/fw",
    "tools/perftest",
    "tools/wiretrace",
    "tools/synctune",
    "tools/firmware-writer",
    "tools/firmware-test",
    "examples",
    "appliance/lib",
    "appliance/cli",
    "appliance/server",
]
exclude = [
    "xtask",
    "firmware/cpu/board",
    "bindings/python",
    "bindings/ffi",
    "simulator",
    "extras/autd3-rs-emulator",
    "extras/autd3-rs-pattern-holo-wgpu",
]

[workspace.package]
version = "0.7.0"
edition = "2024"
license = "MIT"
authors = ["Shun Suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
repository = "https://github.com/shinolab/autd3-sdk"
homepage = "https://shinolab.github.io/autd3-sdk/en/"

[workspace.dependencies]
approx = { version = "0.5.1", default-features = false, features = ["std"] }
core_affinity = { version = "0.8.3", default-features = false }
nalgebra = { version = "0.35.0", default-features = false, features = ["std"] }
rayon = { version = "1.11.0", default-features = false }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
zerocopy = { version = "0.8.52", default-features = false, features = [
    "derive",
] }
tokio = { version = "1.52.3", default-features = false, features = [
    "sync",
    "time",
    "macros",
    "rt",
] }
thread-priority = { version = "3.1.1", default-features = false }
socket2 = { version = "0.6.4", default-features = false }
spin_sleep = { version = "1.3.3", default-features = false }
clap = { version = "4.6.1", default-features = false, features = [
    "std",
    "derive",
    "help",
    "usage",
    "error-context",
] }
humantime = { version = "2.3.0", default-features = false }
mdns-sd = { version = "0.21.0", default-features = false }
axum = { version = "0.8.9", default-features = false, features = [
    "http1",
    "json",
    "tokio",
    "query",
] }
serde = { version = "1.0.228", default-features = false, features = [
    "std",
    "derive",
] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "std",
] }
toml = { version = "1.1.4", default-features = false, features = [
    "parse",
    "serde",
] }
serde_ignored = { version = "0.1.14", default-features = false }
anyhow = { version = "1.0.102", default-features = false, features = ["std"] }
pcap-file = { version = "2.0.0", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-appender = { version = "0.2.3", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false, features = [
    "std",
    "fmt",
    "ansi",
    "env-filter",
] }

autd3-rs = { version = "0.7.0", path = "crates/autd3-rs" }
autd3-cpu-wire = { version = "0.6.0", path = "firmware/cpu/wire" }
autd3-cpu-fw = { version = "0.6.0", path = "firmware/cpu/fw" }
autd3-rs-appliance = { version = "0.7.0", path = "appliance/lib" }
autd3-rs-core = { version = "0.7.0", path = "crates/autd3-rs-core" }
autd3-rs-firmware-emulator = { version = "0.7.0", path = "crates/autd3-rs-firmware-emulator" }
autd3-rs-pattern = { version = "0.7.0", path = "crates/autd3-rs-pattern" }
autd3-rs-pattern-holo = { version = "0.7.0", path = "crates/autd3-rs-pattern-holo" }
autd3-rs-link-echocat = { version = "0.7.0", path = "crates/autd3-rs-link-echocat" }
autd3-rs-link-nop = { version = "0.7.0", path = "crates/autd3-rs-link-nop" }
autd3-rs-link-remote = { version = "0.7.0", path = "crates/autd3-rs-link-remote" }
autd3-rs-link-twincat = { version = "0.7.0", path = "crates/autd3-rs-link-twincat" }
autd3-rs-modulation = { version = "0.7.0", path = "crates/autd3-rs-modulation" }

[workspace.metadata.cargo-semver-checks.lints]
macro_now_doc_hidden = "allow"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
cast_precision_loss = "allow"
struct_excessive_bools = "allow"
