[package]
name = "autd3-rs-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core types shared across the AUTD3 SDK crates."
readme = "README.md"
keywords = ["autd3", "haptics"]
categories = ["science"]

[package.metadata.docs.rs]
all-features = true

[features]
logging = ["dep:tracing-appender", "dep:tracing-subscriber"]
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
autd3-cpu-wire.workspace = true
nalgebra.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror.workspace = true
tracing.workspace = true
tracing-appender = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
zerocopy.workspace = true

[dev-dependencies]
rstest.workspace = true
approx.workspace = true
async-lock.workspace = true
futures-channel.workspace = true
pollster.workspace = true

[lints]
workspace = true
