[workspace]

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
cast_precision_loss = "allow"

[package]
name = "autd3-rs-pattern-holo-wgpu"
version = "0.7.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
authors = ["Shun Suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
repository = "https://github.com/shinolab/autd3-sdk"
homepage = "https://shinolab.github.io/autd3-sdk/en/"
description = "wgpu-based LinAlgBackend for autd3-rs-pattern-holo."
readme = "README.md"
keywords = ["autd3", "haptics"]
categories = ["science"]

[dependencies]
autd3-rs-core = { version = "0.7.0", path = "../../crates/autd3-rs-core" }
autd3-rs-pattern-holo = { version = "0.7.0", path = "../../crates/autd3-rs-pattern-holo" }
nalgebra = { version = "0.35.0", default-features = false, features = ["std"] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
wgpu = { version = "30.0.0", default-features = false, features = [
    "wgsl",
    "vulkan",
    "metal",
    "dx12",
] }
pollster = { version = "1.0.1", default-features = false }
bytemuck = { version = "1.25.0", default-features = false }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }

[dev-dependencies]
autd3-rs-pattern = { path = "../../crates/autd3-rs-pattern" }

[lints]
workspace = true
