[workspace]

[package]
name = "autd3-rs-pattern-holo-wgpu"
version = "0.4.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
authors = ["Shun Suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
repository = "https://github.com/shinolab/autd3-sdk"
description = "wgpu-based LinAlgBackend for autd3-rs-pattern-holo."

[dependencies]
autd3-rs-core = { version = "0.4.0", path = "../../crates/autd3-rs-core" }
autd3-rs-pattern-holo = { version = "0.4.0", path = "../../crates/autd3-rs-pattern-holo" }
nalgebra = { version = "0.35.0", default-features = false, features = ["std"] }
thiserror = "2.0.18"
wgpu = { version = "30.0.0", default-features = false, features = [
    "wgsl",
    "vulkan",
    "metal",
    "dx12",
] }
pollster = "1.0.1"
bytemuck = "1.25.0"

[dev-dependencies]
autd3-rs-pattern = { path = "../../crates/autd3-rs-pattern" }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cast_precision_loss = "allow"
missing_errors_doc = "allow"
