from collections.abc import Callable
from typing import Literal, TypeAlias, final, overload

import polars as pl
from autd3 import Frame
from autd3._autd3 import _Command
from autd3_core import Duration, Geometry, Velocity

_Axis: TypeAlias = float | tuple[float, float]

@final
class Grid:
    def __new__(
        cls,
        x: _Axis,
        y: _Axis,
        z: _Axis,
        resolution: float,
        order: Literal["xyz", "xzy", "yxz", "yzx", "zxy", "zyx"] = "xyz",
    ) -> Grid: ...

@final
class RmsRecordOption:
    sound_speed: Velocity
    def __new__(cls, sound_speed: Velocity | None = None) -> RmsRecordOption: ...

@final
class InstantRecordOption:
    sound_speed: Velocity
    memory_limits_hint_mb: int
    def __new__(
        cls,
        sound_speed: Velocity | None = None,
        time_step: Duration | None = None,
        memory_limits_hint_mb: int = 128,
    ) -> InstantRecordOption: ...

@final
class Rms:
    def observe_points(self) -> pl.DataFrame: ...
    def next(self, duration: Duration) -> pl.DataFrame: ...
    def skip(self, duration: Duration) -> None: ...

@final
class Instant:
    def observe_points(self) -> pl.DataFrame: ...
    def next(self, duration: Duration) -> pl.DataFrame: ...
    def skip(self, duration: Duration) -> None: ...

@final
class Record:
    def num_transducers(self) -> int: ...
    def num_samples(self) -> int: ...
    def phase(self) -> pl.DataFrame: ...
    def pulse_width(self) -> pl.DataFrame: ...
    def output_voltage(self) -> pl.DataFrame: ...
    def output_ultrasound(self) -> pl.DataFrame: ...
    @overload
    def sound_field(self, range: Grid, option: RmsRecordOption) -> Rms: ...
    @overload
    def sound_field(self, range: Grid, option: InstantRecordOption) -> Instant: ...

@final
class Recorder:
    def __new__(cls, geometry: Geometry, start_ns: int = 0) -> Recorder: ...
    def num_devices(self) -> int: ...
    def send(self, command: _Command) -> None: ...
    def send_frame(self, frame: Frame) -> None: ...
    def tick(self, duration: Duration) -> None: ...
    def into_record(self) -> Record: ...

@final
class Emulator:
    def __new__(cls, geometry: Geometry) -> Emulator: ...
    def transducer_table(self) -> pl.DataFrame: ...
    def record(self, callback: Callable[[Recorder], object]) -> Record: ...
