core::arch::global_asm!(
    ".arm",
    ".section .text.__aeabi_memcpy_fast, \"ax\", %progbits",
    ".global __aeabi_memcpy",
    ".global __aeabi_memcpy4",
    ".global __aeabi_memcpy8",
    ".type __aeabi_memcpy, %function",
    ".type __aeabi_memcpy4, %function",
    ".type __aeabi_memcpy8, %function",
    "__aeabi_memcpy:",
    "__aeabi_memcpy4:",
    "__aeabi_memcpy8:",
    "orr r3, r0, r1",
    "tst r3, #3",
    "bne 5f",
    "cmp r2, #32",
    "blo 3f",
    "push {{r4, r5, r6, r7, r8, lr}}",
    "2:",
    "ldmia r1!, {{r3, r4, r5, r6, r7, r8, r12, lr}}",
    "sub r2, r2, #32",
    "stmia r0!, {{r3, r4, r5, r6, r7, r8, r12, lr}}",
    "cmp r2, #32",
    "bhs 2b",
    "pop {{r4, r5, r6, r7, r8, lr}}",
    "3:",
    "cmp r2, #4",
    "blo 5f",
    "4:",
    "ldr r3, [r1], #4",
    "sub r2, r2, #4",
    "str r3, [r0], #4",
    "cmp r2, #4",
    "bhs 4b",
    "5:",
    "cmp r2, #0",
    "bxeq lr",
    "6:",
    "ldrb r3, [r1], #1",
    "subs r2, r2, #1",
    "strb r3, [r0], #1",
    "bne 6b",
    "bx lr",
);
