[package]
name = "autd3-rs-link-ethercrab"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "EtherCrab-backed Link implementation for autd3-rs."

[dependencies]
autd3-rs-core.workspace = true
core_affinity.workspace = true
thiserror.workspace = true
thread-priority.workspace = true
ethercrab = { version = "0.7.1", default-features = false, features = ["std"] }
futures-util = { version = "0.3.32", default-features = false, features = ["alloc"] }
tokio = { workspace = true, features = ["sync", "time", "macros", "rt", "net"] }
pcap = { version = "2.4.0", default-features = false }
tracing = { workspace = true, features = ["log"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2.186"

[target.'cfg(target_os = "windows")'.dependencies]
spin_sleep = "1.3.3"

[target.'cfg(target_os = "windows")'.build-dependencies]
cc = "1.2.65"

[dev-dependencies]
tokio = { workspace = true, features = [
    "sync",
    "time",
    "macros",
    "rt",
    "rt-multi-thread",
] }

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
async-io = "2.6.0"
