[package]
name = "autd3-rs-perftest"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false
description = "CLI tool for measuring communication performance."

[[bin]]
name = "autd3-rs-perftest"
path = "src/main.rs"

[features]
mem-profile = []

[dependencies]
autd3-rs = { workspace = true, features = ["emulator", "logging"] }
clap.workspace = true
core_affinity.workspace = true
humantime.workspace = true
anyhow.workspace = true
thread-priority.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros", "rt", "rt-multi-thread", "signal"] }

[lints]
workspace = true
