[package]
name = "autd3-rs-perftest"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false
description = "CLI tool for measuring EtherCAT-link performance."

[[bin]]
name = "autd3-rs-perftest"
path = "src/main.rs"

[features]
mem-profile = []

[dependencies]
autd3-rs = { workspace = true, features = ["logging"] }
autd3-rs-link-echocat.workspace = true
autd3-rs-link-nop.workspace = true
autd3-rs-link-remote.workspace = true
autd3-rs-link-twincat.workspace = true
clap.workspace = true
humantime.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros", "rt", "rt-multi-thread", "signal"] }

[lints]
workspace = true
