"""Generate `inc/params_fpga.h` from the FPGA `params.svh`.

The FPGA `params.svh` is the single source of truth for hardware constants
(transducer count, BRAM addresses, control-flag bits, enum values, ...). This
script parses its `localparam` definitions and `typedef enum` blocks and emits
matching C `#define`s so the CPU firmware can stay in lock-step with the FPGA.

Run it from anywhere: `python3 gen_param.py` (paths are resolved relative to
this file). Ported from the legacy `autd3-firmware` CPU build.
"""

import pathlib
import re
import subprocess

HERE = pathlib.Path(__file__).resolve().parent
PARAMS_SVH = (
    HERE.parent / "fpga" / "rtl" / "sources_1" / "new" / "headers" / "params.svh"
)
OUT = HERE / "inc" / "params_fpga.h"


def to_upper(name: str) -> str:
    name = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    name = re.sub("([a-z0-9])([A-Z])", r"\1_\2", name)
    return name.upper()


class Const:
    def __init__(self: "Const", name: str, value: str) -> None:
        self.name = name
        self.value = value


class Enum:
    def __init__(self: "Enum", name: str, consts: list[Const]) -> None:
        self.name = name
        self.consts = consts


consts: list[Const] = []
enums: list[Enum] = []

with pathlib.Path.open(PARAMS_SVH, "r") as f:
    read_enum = False
    enum_consts: list[Const] = []
    for raw in f.readlines():
        line = raw.strip()
        localparam = re.match(
            r"localparam (.+) (\w+) = (\d+|\d+'[bhd][\da-fA-F]+|\d+.\d+);", line
        )
        if localparam:
            consts.append(Const(to_upper(localparam.group(2)), localparam.group(3)))
        elif line.startswith("typedef enum"):
            read_enum = True
            enum_consts = []

            param = re.match(r".*{(\w+)\s+=\s+(\d+|\d+'[bhd][\da-fA-F]+)}.*", line)
            if param:
                enum_consts.append(Const(param.group(1), param.group(2)))
            if "}" in line:
                read_enum = False
                enum_name = re.match(r".*} (\w+);", line).group(1)
                enums.append(Enum(enum_name, enum_consts))
        elif read_enum:
            if line.startswith("}"):
                read_enum = False
                enum_name = re.match(r"} (\w+);", line).group(1)
                enums.append(Enum(enum_name, enum_consts))
            else:
                param = re.match(r"(\w+)\s+=\s+(\d+|\d+'[bhd][\da-fA-F]+),?$", line)
                if param:
                    enum_consts.append(Const(param.group(1), param.group(2)))


def to_value(value: str) -> str:
    """Convert a SystemVerilog sized literal to a C hex literal, honoring the
    base prefix (`'b`/`'h`/`'d`). Plain decimals are passed through."""
    match = re.fullmatch(r"\d+'([bhd])([\da-fA-F]+)", value)
    if match:
        base = {"b": 2, "h": 16, "d": 10}[match.group(1)]
        return f"0x{int(match.group(2), base):X}"
    return value


with pathlib.Path.open(OUT, "w") as f:
    f.writelines(
        f"""/* AUTO-GENERATED by gen_param.py from
 * {PARAMS_SVH.relative_to(HERE.parent.parent)}. DO NOT EDIT. */
#ifndef PARAMS_FPGA_H
#define PARAMS_FPGA_H
"""
    )

    for const in consts:
        f.writelines(
            f"""
#define {const.name} ({to_value(const.value)})"""
        )

    for enum in enums:
        f.writelines("\n")
        for const in enum.consts:
            f.writelines(
                f"""
#define {const.name} ({to_value(const.value)})"""
            )
            if enum.name.endswith("bit_t"):
                f.writelines(
                    f"""
#define {const.name.replace("_BIT", "")} (1 << {const.name})"""
                )

    f.writelines(
        """

#endif  // PARAMS_FPGA_H
"""
    )

subprocess.run(["clang-format", "--style=file", "-i", str(OUT)], check=True)  # noqa: S603, S607
