[package]
name = "autd3-rs-examples"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "examples for autd3-rs."
publish = false

[dependencies]
autd3-rs = { workspace = true, features = ["legacy", "logging"] }
autd3-rs-pattern.workspace = true
autd3-rs-pattern-holo.workspace = true
autd3-rs-link-echocat.workspace = true
autd3-rs-link-remote.workspace = true
autd3-rs-modulation.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = [
    "time",
    "macros",
    "rt",
    "rt-multi-thread",
    "signal",
] }

[lints]
workspace = true
