// AUTO-GENERATED by `cargo xtask cpu gen-param` from
// firmware/fpga/rtl/sources_1/new/headers/params.svh. DO NOT EDIT.
// Firmware-internal FPGA register map.

pub use autd3_cpu_wire::fpga_params::*;
pub const SYNC_CYCLE_TICKS: u16 = 20480;
pub const FLASH_BUF_BYTES: usize = 1024;

bitflags::bitflags! {
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub struct CtlFlags: u16 {
        const MOD_SET = 1 << 0;
        const PATTERN_SET = 1 << 1;
        const SILENCER_SET = 1 << 2;
        const DEBUG_SET = 1 << 4;
        const SYNC_SET = 1 << 5;
        const GPIO_IN_0 = 1 << 8;
        const GPIO_IN_1 = 1 << 9;
        const GPIO_IN_2 = 1 << 10;
        const GPIO_IN_3 = 1 << 11;
        const FAILSAFE = 1 << 12;
        const FORCE_FAN = 1 << 13;
    }
}

autd3_cpu_wire::wire_enum_u8! {
    pub enum BramSelect {
        Controller = 0x0,
        PhaseCorr = 0x1,
        OutputMask = 0x2,
        Flash = 0x3,
        FlashBuf = 0x4,
        PweTable = 0x6,
        Mod = 0x40,
        Emission = 0xC0,
    }
}

pub const ADDR_FLASH_CMD: u16 = 0x0;
pub const ADDR_FLASH_ADDR_0: u16 = 0x1;
pub const ADDR_FLASH_ADDR_1: u16 = 0x2;
pub const ADDR_FLASH_LEN_0: u16 = 0x3;
pub const ADDR_FLASH_LEN_1: u16 = 0x4;
pub const ADDR_FLASH_STATUS: u16 = 0x5;
pub const ADDR_FLASH_RESULT_0: u16 = 0x6;
pub const ADDR_FLASH_RESULT_1: u16 = 0x7;
pub const ADDR_FLASH_USR_ACCESS_0: u16 = 0x8;
pub const ADDR_FLASH_USR_ACCESS_1: u16 = 0x9;

autd3_cpu_wire::wire_enum_u8! {
    pub enum FlashOp {
        Crc32 = 0x2,
        Erase = 0x3,
        Program = 0x4,
        Reboot = 0x5,
    }
}

autd3_cpu_wire::wire_enum_u8! {
    pub enum FlashErr {
        None = 0x0,
        Protected = 0x1,
        Timeout = 0x2,
        Invalid = 0x3,
    }
}

pub const ADDR_CTL_FLAG: u16 = 0x0;
pub const ADDR_FPGA_STATE: u16 = 0x1;
pub const ADDR_VERSION_NUM_MAJOR: u16 = 0x2;
pub const ADDR_VERSION_NUM_MINOR: u16 = 0x3;
pub const ADDR_VERSION_NUM_PATCH: u16 = 0x4;
pub const ADDR_FUNCTION_BITS: u16 = 0x5;
pub const ADDR_SILENCER_SET_RESULT: u16 = 0x6;
pub const ADDR_SYNC_TIME_0: u16 = 0x10;
pub const ADDR_SYNC_TIME_1: u16 = 0x11;
pub const ADDR_SYNC_TIME_2: u16 = 0x12;
pub const ADDR_SYNC_TIME_3: u16 = 0x13;
pub const ADDR_MOD_MEM_WR_BANK: u16 = 0x20;
pub const ADDR_MOD_MEM_WR_PAGE: u16 = 0x21;
pub const ADDR_MOD_REQ_RD_BANK: u16 = 0x22;
pub const ADDR_MOD_CYCLE0: u16 = 0x23;
pub const ADDR_MOD_CYCLE1: u16 = 0x24;
pub const ADDR_MOD_FREQ_DIV0: u16 = 0x25;
pub const ADDR_MOD_FREQ_DIV1: u16 = 0x26;
pub const ADDR_MOD_REP0: u16 = 0x27;
pub const ADDR_MOD_REP1: u16 = 0x28;
pub const ADDR_MOD_TRANSITION_MODE: u16 = 0x29;
pub const ADDR_MOD_TRANSITION_VALUE_0: u16 = 0x2A;
pub const ADDR_MOD_TRANSITION_VALUE_1: u16 = 0x2B;
pub const ADDR_MOD_TRANSITION_VALUE_2: u16 = 0x2C;
pub const ADDR_MOD_TRANSITION_VALUE_3: u16 = 0x2D;
pub const ADDR_SILENCER_FLAG: u16 = 0x40;
pub const ADDR_SILENCER_UPDATE_RATE_INTENSITY: u16 = 0x41;
pub const ADDR_SILENCER_UPDATE_RATE_PHASE: u16 = 0x42;
pub const ADDR_SILENCER_COMPLETION_STEPS_INTENSITY: u16 = 0x43;
pub const ADDR_SILENCER_COMPLETION_STEPS_PHASE: u16 = 0x44;
pub const ADDR_PATTERN_MEM_WR_BANK: u16 = 0x50;
pub const ADDR_PATTERN_MEM_WR_PAGE: u16 = 0x51;
pub const ADDR_PATTERN_REQ_RD_BANK: u16 = 0x52;
pub const ADDR_PATTERN_CYCLE0: u16 = 0x53;
pub const ADDR_PATTERN_CYCLE1: u16 = 0x54;
pub const ADDR_PATTERN_FREQ_DIV0: u16 = 0x55;
pub const ADDR_PATTERN_FREQ_DIV1: u16 = 0x56;
pub const ADDR_PATTERN_REP0: u16 = 0x57;
pub const ADDR_PATTERN_REP1: u16 = 0x58;
pub const ADDR_PATTERN_MODE0: u16 = 0x59;
pub const ADDR_PATTERN_MODE1: u16 = 0x5A;
pub const ADDR_PATTERN_SOUND_SPEED0: u16 = 0x5B;
pub const ADDR_PATTERN_SOUND_SPEED1: u16 = 0x5C;
pub const ADDR_PATTERN_NUM_FOCI0: u16 = 0x5D;
pub const ADDR_PATTERN_NUM_FOCI1: u16 = 0x5E;
pub const ADDR_PATTERN_TRANSITION_MODE: u16 = 0x5F;
pub const ADDR_PATTERN_TRANSITION_VALUE_0: u16 = 0x60;
pub const ADDR_PATTERN_TRANSITION_VALUE_1: u16 = 0x61;
pub const ADDR_PATTERN_TRANSITION_VALUE_2: u16 = 0x62;
pub const ADDR_PATTERN_TRANSITION_VALUE_3: u16 = 0x63;
pub const ADDR_DEBUG_VALUE0_0: u16 = 0xF0;
pub const ADDR_DEBUG_VALUE0_1: u16 = 0xF1;
pub const ADDR_DEBUG_VALUE0_2: u16 = 0xF2;
pub const ADDR_DEBUG_VALUE0_3: u16 = 0xF3;
pub const ADDR_DEBUG_VALUE1_0: u16 = 0xF4;
pub const ADDR_DEBUG_VALUE1_1: u16 = 0xF5;
pub const ADDR_DEBUG_VALUE1_2: u16 = 0xF6;
pub const ADDR_DEBUG_VALUE1_3: u16 = 0xF7;
pub const ADDR_DEBUG_VALUE2_0: u16 = 0xF8;
pub const ADDR_DEBUG_VALUE2_1: u16 = 0xF9;
pub const ADDR_DEBUG_VALUE2_2: u16 = 0xFA;
pub const ADDR_DEBUG_VALUE2_3: u16 = 0xFB;
pub const ADDR_DEBUG_VALUE3_0: u16 = 0xFC;
pub const ADDR_DEBUG_VALUE3_1: u16 = 0xFD;
pub const ADDR_DEBUG_VALUE3_2: u16 = 0xFE;
pub const ADDR_DEBUG_VALUE3_3: u16 = 0xFF;
