use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use clap::Subcommand;

use crate::util::{on_path, run};

const PROJECT_NAME: &str = "autd3-fpga";

pub const VERIBLE_COLUMN_LIMIT: &str = "--column_limit=150";

#[derive(Subcommand)]
pub enum FpgaCmd {
    /// Generate the Vivado project
    Project,
    /// Synthesize, implement, and write the bitstream / `autd3-fpga.mcs`
    Build {
        /// Re-synthesize even when a bitstream already exists
        #[arg(long)]
        force: bool,
    },
    /// Build, then configure the SPI flash of the device
    Flash {
        /// Re-synthesize even when a bitstream already exists
        #[arg(long)]
        force: bool,
    },
    /// Run the Vivado simulation testbenches
    Sim {
        /// Only run this testbench (all of them if omitted)
        #[arg(long)]
        tb: Option<String>,
    },
    /// Format the RTL sources with `verible-verilog-format`
    Format {
        /// Rewrite the files instead of only checking them
        #[arg(long)]
        fix: bool,
    },
    /// Regenerate `controller.sv` (the register state machine)
    GenController,
    /// Copy the IP generated by Vivado back into `rtl/sources_1/ip`
    CommitIps,
    /// Remove the Vivado project and its build outputs
    Clean,
}

pub fn run_fpga(root: &Path, cmd: &FpgaCmd) -> Result<()> {
    let fpga_dir = root.join("firmware/fpga");
    match cmd {
        FpgaCmd::Project => fpga_project(&fpga_dir),
        FpgaCmd::Build { force } => fpga_build(root, *force).map(|_| ()),
        FpgaCmd::Flash { force } => fpga_flash(root, *force),
        FpgaCmd::Sim { tb } => fpga_sim(&fpga_dir, tb.as_deref()),
        FpgaCmd::Format { fix } => fpga_format(&fpga_dir, *fix),
        FpgaCmd::GenController => crate::fpga_codegen::gen_controller(&fpga_dir),
        FpgaCmd::CommitIps => fpga_commit_ips(&fpga_dir),
        FpgaCmd::Clean => fpga_clean(&fpga_dir),
    }
}

fn fpga_sim(fpga_dir: &Path, tb: Option<&str>) -> Result<()> {
    let vivado = resolve_vivado()?;

    if !fpga_dir.join(format!("{PROJECT_NAME}.xpr")).exists() {
        fpga_project(fpga_dir)?;
    }

    let mut args = vec![
        "-mode".to_string(),
        "batch".to_string(),
        "-source".to_string(),
        "scripts/sim.tcl".to_string(),
    ];
    if let Some(tb) = tb {
        args.push("-tclargs".to_string());
        args.extend(tb.split_whitespace().map(str::to_string));
    }
    run(&vivado, args, fpga_dir)
        .context("xsim reported testbench failures (see the SUMMARY table above)")
}

fn fpga_format(fpga_dir: &Path, fix: bool) -> Result<()> {
    if !on_path("verible-verilog-format") {
        bail!(
            "verible-verilog-format not found on PATH. Install Verible \
             (https://github.com/chipsalliance/verible)."
        );
    }

    let rtl_dir = fpga_dir.join("rtl");
    let mut files = Vec::new();
    collect_rtl_sources(&rtl_dir, &mut files)?;
    files.sort();
    if files.is_empty() {
        bail!("no SystemVerilog sources found under {}", rtl_dir.display());
    }

    if fix {
        let mut args = vec![VERIBLE_COLUMN_LIMIT.to_string(), "--inplace".to_string()];
        args.extend(files.iter().map(|p| p.to_string_lossy().into_owned()));
        return run("verible-verilog-format", args, fpga_dir)
            .context("verible-verilog-format failed");
    }

    // `--verify` only accepts a single file, so check them one by one.
    let mut unformatted = 0usize;
    for file in &files {
        let args = [VERIBLE_COLUMN_LIMIT, "--verify", &file.to_string_lossy()];
        if run("verible-verilog-format", args, fpga_dir).is_err() {
            unformatted += 1;
        }
    }
    if unformatted > 0 {
        bail!(
            "{unformatted} RTL source(s) are not formatted; run `cargo xtask fpga format --fix`"
        );
    }
    Ok(())
}

fn collect_rtl_sources(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in std::fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .flatten()
    {
        let path = entry.path();
        if path.is_dir() {
            collect_rtl_sources(&path, out)?;
        } else if path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| e == "sv" || e == "svh")
        {
            out.push(path);
        }
    }
    Ok(())
}

fn fpga_project(fpga_dir: &Path) -> Result<()> {
    let vivado = resolve_vivado()?;
    run(
        &vivado,
        ["-mode", "batch", "-source", "scripts/proj_gen.tcl"],
        fpga_dir,
    )
}

pub fn fpga_build(root: &Path, force: bool) -> Result<PathBuf> {
    let fpga_dir = root.join("firmware/fpga");
    let vivado = resolve_vivado()?;

    if !fpga_dir.join(format!("{PROJECT_NAME}.xpr")).exists() {
        fpga_project(&fpga_dir)?;
    }

    let jobs = std::thread::available_parallelism().map_or(1, std::num::NonZero::get);
    let mut args = vec![
        "-mode".to_string(),
        "batch".to_string(),
        "-source".to_string(),
        "scripts/build.tcl".to_string(),
        "-tclargs".to_string(),
        jobs.to_string(),
    ];
    if force {
        args.push("force".to_string());
    }
    run(&vivado, args, &fpga_dir)?;

    let mcs = fpga_dir.join(format!("{PROJECT_NAME}.mcs"));
    if !mcs.is_file() {
        bail!("Vivado finished but {} was not created", mcs.display());
    }
    println!("fpga built: {}", mcs.display());
    Ok(mcs)
}

fn fpga_flash(root: &Path, force: bool) -> Result<()> {
    let mcs = fpga_build(root, force)?;
    let vivado = resolve_vivado()?;
    let fpga_dir = root.join("firmware/fpga");
    println!("Make sure the configuration cable is connected and the AUTD3 power is on.");
    run(
        &vivado,
        ["-mode", "batch", "-source", "scripts/configuration.tcl"],
        &fpga_dir,
    )
    .context("Vivado failed. Make sure the AUTD3 is connected and powered on.")?;
    println!("flash complete: {}", mcs.display());
    Ok(())
}

pub fn resolve_vivado() -> Result<String> {
    if on_path("vivado") {
        return Ok("vivado".to_string());
    }
    #[cfg(windows)]
    if let Some(path) = find_vivado_windows() {
        return Ok(path);
    }
    bail!(
        "Vivado not found. Put `vivado` on PATH (source Vivado's `settings64` script) \
         or install it so it can be auto-detected."
    );
}

#[cfg(windows)]
fn find_vivado_windows() -> Option<String> {
    use winreg::enums::HKEY_LOCAL_MACHINE;
    use winreg::RegKey;

    const NEEDLES: [&str; 4] = [
        "Vivado",
        "Vitis",
        "Xilinx Design Tools FPGAs",
        "AMDDesignTools",
    ];

    let uninstall = RegKey::predef(HKEY_LOCAL_MACHINE)
        .open_subkey(r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall")
        .ok()?;

    let mut install_location: Option<String> = None;
    for subkey_name in uninstall.enum_keys().flatten() {
        let Ok(subkey) = uninstall.open_subkey(&subkey_name) else {
            continue;
        };
        let display_name: String = subkey.get_value("DisplayName").unwrap_or_default();
        if NEEDLES.iter().any(|n| display_name.contains(n)) {
            if let Ok(loc) = subkey.get_value::<String, _>("InstallLocation") {
                install_location = Some(loc);
            }
        }
    }

    let install = PathBuf::from(install_location?);
    let vivado_dir = find_vivado_2025(&install).or_else(|| find_vivado_2024(&install))?;
    Some(
        vivado_dir
            .join("bin")
            .join("vivado.bat")
            .to_string_lossy()
            .into_owned(),
    )
}

#[cfg(windows)]
fn find_vivado_2024(install: &Path) -> Option<PathBuf> {
    let vivado = install.join("Vivado");
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(vivado)
        .ok()?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();
    dirs.pop()
}

#[cfg(windows)]
fn find_vivado_2025(install: &Path) -> Option<PathBuf> {
    fn recurse(dir: &Path, depth: usize, out: &mut Vec<PathBuf>) {
        if depth > 2 {
            return;
        }
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.eq_ignore_ascii_case("vivado"))
                {
                    out.push(path.clone());
                }
                recurse(&path, depth + 1, out);
            }
        }
    }
    let mut found = Vec::new();
    recurse(install, 0, &mut found);
    found.sort();
    found.pop()
}

fn fpga_commit_ips(fpga_dir: &Path) -> Result<()> {
    let src = fpga_dir.join(format!("{PROJECT_NAME}.srcs/sources_1/ip"));
    let dst = fpga_dir.join("rtl/sources_1/ip");
    if !src.is_dir() {
        bail!(
            "{} does not exist; generate the Vivado project first (`cargo xtask fpga project`)",
            src.display()
        );
    }
    copy_dir(&src, &dst)?;
    println!("committed IP: {} -> {}", src.display(), dst.display());
    Ok(())
}

fn copy_dir(src: &Path, dst: &Path) -> Result<()> {
    std::fs::create_dir_all(dst).with_context(|| format!("creating {}", dst.display()))?;
    for entry in std::fs::read_dir(src)
        .with_context(|| format!("reading {}", src.display()))?
        .flatten()
    {
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_dir(&from, &to)?;
        } else {
            std::fs::copy(&from, &to)
                .with_context(|| format!("copying {} -> {}", from.display(), to.display()))?;
        }
    }
    Ok(())
}

fn fpga_clean(fpga_dir: &Path) -> Result<()> {
    const FILE_EXTS: [&str; 8] = ["jou", "log", "zip", "prm", "str", "pb", "mcs", "xpr"];

    let entries =
        std::fs::read_dir(fpga_dir).with_context(|| format!("reading {}", fpga_dir.display()))?;
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        let remove = if path.is_dir() {
            name == ".Xil" || name.starts_with("autd3-fpga.")
        } else {
            path.extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| FILE_EXTS.contains(&e))
        };
        if remove {
            if path.is_dir() {
                std::fs::remove_dir_all(&path)
                    .with_context(|| format!("removing {}", path.display()))?;
            } else {
                std::fs::remove_file(&path)
                    .with_context(|| format!("removing {}", path.display()))?;
            }
            println!("removed {}", path.display());
        }
    }
    Ok(())
}
