[package]
name = "console"
version = "0.6.0"
description = "GUI console that launches AUTD3 tools (simulator / firmware / TwinCAT setup)"
repository = "https://github.com/shinolab/autd3-sdk"
license = "MIT"
binaries = ["autd3-console", "autd3-rs-simulator", "autd3-firmware", "autd3-appliance"]
out-dir = "target/distrib"
build-command = [
    "cargo",
    "run",
    "--quiet",
    "--manifest-path",
    "../xtask/Cargo.toml",
    "--",
    "console",
    "stage",
]
