from collections.abc import Iterator, Sequence
from typing import Any, ClassVar, Protocol, SupportsComplex, TypeAlias, final

import numpy as np
import numpy.typing as npt
from autd3_pattern import IntensityBuffer, PhaseBuffer

_Vec3: TypeAlias = Sequence[float] | npt.NDArray[np.floating[Any]]
_Quaternion: TypeAlias = Sequence[float] | npt.NDArray[np.floating[Any]]

class _ScipyRotation(Protocol):
    def as_quat(self) -> Any: ...

_Rotation: TypeAlias = _Quaternion | EulerAngles | _ScipyRotation

class Autd3Error(Exception):
    GENERIC: ClassVar[int]
    TIMEOUT: ClassVar[int]
    DEVICE: ClassVar[int]
    NETWORK: ClassVar[int]
    INVALID_ARGUMENT: ClassVar[int]
    UNSUPPORTED_FIRMWARE: ClassVar[int]
    code: int

@final
class Freq:
    @staticmethod
    def from_hz(freq: float) -> Freq: ...
    @property
    def hz(self) -> float: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def hz_int(self) -> int | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Velocity:
    @staticmethod
    def from_mm_s(mm_per_s: float) -> Velocity: ...
    @staticmethod
    def from_m_s(m_per_s: float) -> Velocity: ...
    @property
    def mm_s(self) -> float: ...
    @property
    def m_s(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Angle:
    ZERO: ClassVar[Angle]
    @staticmethod
    def from_rad(radian: float) -> Angle: ...
    @staticmethod
    def from_deg(degree: float) -> Angle: ...
    @property
    def rad(self) -> float: ...
    @property
    def deg(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Length:
    @staticmethod
    def from_mm(millimetres: float) -> Length: ...
    @staticmethod
    def from_m(metres: float) -> Length: ...
    @property
    def mm(self) -> float: ...
    @property
    def m(self) -> float: ...
    def __truediv__(self, rhs: _SecUnit) -> Velocity: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _FreqUnit:
    def __rmul__(self, lhs: float) -> Freq: ...

@final
class _LengthUnit:
    def __rmul__(self, lhs: float) -> Length: ...

@final
class _AngleUnit:
    def __rmul__(self, lhs: float) -> Angle: ...

@final
class _SecUnit: ...

Hz: _FreqUnit
kHz: _FreqUnit
m: _LengthUnit
mm: _LengthUnit
s: _SecUnit
deg: _AngleUnit
rad: _AngleUnit

@final
class Duration:
    @staticmethod
    def from_nanos(nanos: int) -> Duration: ...
    @staticmethod
    def from_micros(micros: int) -> Duration: ...
    @staticmethod
    def from_millis(millis: int) -> Duration: ...
    @staticmethod
    def from_secs(secs: int) -> Duration: ...
    @staticmethod
    def from_secs_f64(secs: float) -> Duration: ...
    def as_nanos(self) -> int: ...
    def as_micros(self) -> int: ...
    def as_millis(self) -> int: ...
    def as_secs_f64(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Duration) -> bool: ...
    def __le__(self, other: Duration) -> bool: ...
    def __gt__(self, other: Duration) -> bool: ...
    def __ge__(self, other: Duration) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Intensity:
    MAX: ClassVar[Intensity]
    MIN: ClassVar[Intensity]
    def __new__(cls, value: int) -> Intensity: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Intensity) -> bool: ...
    def __le__(self, other: Intensity) -> bool: ...
    def __gt__(self, other: Intensity) -> bool: ...
    def __ge__(self, other: Intensity) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Phase:
    ZERO: ClassVar[Phase]
    PI: ClassVar[Phase]
    def __new__(cls, value: int | Angle | complex | SupportsComplex) -> Phase: ...
    @property
    def value(self) -> int: ...
    def rad(self) -> float: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Nearest:
    def __new__(cls, value: Freq | Duration) -> Nearest: ...
    def nearest_hz(self) -> float | None: ...
    def nearest_nanos(self) -> int | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class SamplingConfig:
    FREQ_4K: ClassVar[SamplingConfig]
    FREQ_40K: ClassVar[SamplingConfig]
    def __new__(cls, value: int | Freq | Duration | Nearest) -> SamplingConfig: ...
    def divide(self) -> int: ...
    def freq(self) -> Freq: ...
    def period(self) -> Duration: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class EulerAngles:
    @staticmethod
    def XYZ(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def XZY(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def YXZ(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def YZX(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def ZXY(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def ZYX(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def XYX(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def XZX(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def YXY(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def YZY(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def ZXZ(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...
    @staticmethod
    def ZYZ(first: Angle, second: Angle, third: Angle) -> EulerAngles: ...

@final
class Autd3:
    NUM_TRANSDUCERS: ClassVar[int]
    GRID_X: ClassVar[int]
    GRID_Y: ClassVar[int]
    PITCH_MM: ClassVar[float]
    DEVICE_WIDTH: ClassVar[float]
    DEVICE_HEIGHT: ClassVar[float]
    def __new__(cls, origin: _Vec3, rotation: _Rotation | None = None) -> Autd3: ...
    @property
    def origin(self) -> npt.NDArray[np.float32]: ...
    @property
    def rotation(self) -> npt.NDArray[np.float32]: ...
    def __eq__(self, other: object) -> bool: ...

def point(x: Length, y: Length, z: Length) -> npt.NDArray[np.float32]: ...
def offset(x: Length, y: Length, z: Length) -> npt.NDArray[np.float32]: ...

@final
class Device:
    def idx(self) -> int: ...
    def num_transducers(self) -> int: ...
    def is_empty(self) -> bool: ...
    def _capsule(self) -> object: ...
    def to_local(self, point: _Vec3) -> npt.NDArray[np.float32]: ...
    def center(self) -> npt.NDArray[np.float32]: ...
    def positions(self) -> npt.NDArray[np.float32]: ...
    def directions(self) -> npt.NDArray[np.float32]: ...
    def position(self, index: int) -> npt.NDArray[np.float32]: ...
    def direction(self, index: int) -> npt.NDArray[np.float32]: ...
    def rotation(self) -> npt.NDArray[np.float32]: ...
    def x_direction(self) -> npt.NDArray[np.float32]: ...
    def y_direction(self) -> npt.NDArray[np.float32]: ...
    def axial_direction(self) -> npt.NDArray[np.float32]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> npt.NDArray[np.float32]: ...
    def __eq__(self, other: object) -> bool: ...

@final
class Geometry:
    def __new__(cls, devices: Sequence[Autd3]) -> Geometry: ...
    @staticmethod
    def from_json(json: str) -> Geometry: ...
    def to_json(self) -> str: ...
    def center(self) -> npt.NDArray[np.float32]: ...
    def num_devices(self) -> int: ...
    def is_empty(self) -> bool: ...
    def num_transducers(self) -> int: ...
    def phase_buffer(self) -> PhaseBuffer: ...
    def intensity_buffer(self) -> IntensityBuffer: ...
    def device(self, index: int) -> Device: ...
    def __getitem__(self, index: int) -> Device: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Device]: ...
    def __eq__(self, other: object) -> bool: ...
