// AUTO-GENERATED by `cargo xtask cpu gen-param` from
// firmware/fpga/rtl/sources_1/new/headers/params.svh and the IP .xci files. DO NOT EDIT.
// Client-facing wire constants shared with the firmware.

pub const NUM_TRANSDUCERS: usize = 249;
pub const NUM_BANKS: usize = 2;
pub const EMISSION_MAX_INDICES: u32 = 1024;
pub const EMISSION_SLOT_WORDS: usize = 256;
pub const FOCUS_WORDS: usize = 4;
pub const NUM_FOCI_MAX: u8 = 8;
pub const ULTRASOUND_FREQ_HZ: u32 = 40000;
pub const REP_INFINITE: u16 = 0xFFFF;
pub const FLASH_WRITABLE_BASE: u32 = 0x80_0000;
pub const FLASH_END: u32 = 0x100_0000;
pub const FLASH_IMAGE_BASE: u32 = 0x80_0100;
pub const FLASH_USR_ACCESS_GOLDEN: u32 = 0x474F_4C44;
pub const FLASH_USR_ACCESS_UPDATE: u32 = 0x5550_4454;
pub const VERSION_NUM_MAJOR: u8 = 0x0;
pub const VERSION_NUM_MINOR: u8 = 0xA;
pub const VERSION_NUM_PATCH: u8 = 0x0;

bitflags::bitflags! {
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub struct FunctionBits: u8 {
        const DYNAMIC_FREQ = 1 << 1;
        const FLASH_OTA = 1 << 2;
        const STRICT_SILENCER_GUARD = 1 << 3;
        const EMULATOR = 1 << 7;
    }
}

bitflags::bitflags! {
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub struct FpgaStateFlags: u8 {
        const THERMAL_ASSERT = 1 << 0;
        const MOD_BANK = 1 << 1;
        const PATTERN_BANK = 1 << 2;
        const PATTERN_MODE = 1 << 3;
        const PATTERN_STOPPED = 1 << 4;
        const MOD_STOPPED = 1 << 5;
        const TRANSITION_PENDING = 1 << 6;
        const FAILSAFE = 1 << 7;
    }
}

crate::wire_enum_u8! {
    pub enum TransitionMode {
        SyncIdx = 0x0,
        SysTime = 0x1,
        Gpio = 0x2,
        Ext = 0xF0,
        Immediate = 0xFF,
    }
}

crate::wire_enum_u8! {
    pub enum EmissionType {
        Foci = 0x0,
        Raw = 0x1,
    }
}

bitflags::bitflags! {
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub struct SilencerFlags: u8 {
        const FIXED_UPDATE_RATE_MODE = 1 << 0;
        const STRICT_MODE = 1 << 1;
    }
}

crate::wire_enum_u8! {
    pub enum GpioOutType {
        None = 0x0,
        BaseSig = 0x1,
        Thermo = 0x2,
        ForceFan = 0x3,
        Sync = 0x10,
        SyncRaw = 0x11,
        ModBank = 0x20,
        ModIdx = 0x21,
        PatternBank = 0x50,
        PatternIdx = 0x51,
        IsStmMode = 0x52,
        SysTimeEq = 0x60,
        SyncDiff = 0x70,
        PwmOut = 0xE0,
        Direct = 0xF0,
    }
}

pub const MOD_BUFFER_SAMPLES: usize = 65536;
pub const PWE_TABLE_SIZE: usize = 256;

pub const FOCUS_TR_X_MAX: i32 = 6909;
pub const FOCUS_TR_Y_MAX: i32 = 5283;

pub const FPGA_CLK_FREQ_HZ: u32 = 20_480_000;
