// AUTO-GENERATED by `cargo xtask cpu gen-param` from
// firmware/fpga/rtl/sources_1/new/headers/params.svh and the BRAM IP .xci files. DO NOT EDIT.
// Client-facing wire constants shared with the firmware.

pub const NUM_TRANSDUCERS: usize = 249;
pub const NUM_BANKS: usize = 2;
pub const EMISSION_MAX_INDICES: u32 = 1024;
pub const NUM_FOCI_MAX: u8 = 8;
pub const VERSION_NUM_MAJOR: u8 = 0x0;
pub const VERSION_NUM_MINOR: u8 = 0x3;
pub const VERSION_NUM_PATCH: u8 = 0x0;

pub const TRANSITION_MODE_SYNC_IDX: u8 = 0x0;
pub const TRANSITION_MODE_SYS_TIME: u8 = 0x1;
pub const TRANSITION_MODE_GPIO: u8 = 0x2;
pub const TRANSITION_MODE_EXT: u8 = 0xF0;
pub const TRANSITION_MODE_IMMEDIATE: u8 = 0xFF;

pub const EMISSION_TYPE_FOCI: u8 = 0x0;
pub const EMISSION_TYPE_RAW: u8 = 0x1;

pub const GPIO_O_TYPE_NONE: u8 = 0x0;
pub const GPIO_O_TYPE_BASE_SIG: u8 = 0x1;
pub const GPIO_O_TYPE_THERMO: u8 = 0x2;
pub const GPIO_O_TYPE_FORCE_FAN: u8 = 0x3;
pub const GPIO_O_TYPE_SYNC: u8 = 0x10;
pub const GPIO_O_TYPE_MOD_BANK: u8 = 0x20;
pub const GPIO_O_TYPE_MOD_IDX: u8 = 0x21;
pub const GPIO_O_TYPE_PATTERN_BANK: u8 = 0x50;
pub const GPIO_O_TYPE_PATTERN_IDX: u8 = 0x51;
pub const GPIO_O_TYPE_IS_STM_MODE: u8 = 0x52;
pub const GPIO_O_TYPE_SYS_TIME_EQ: u8 = 0x60;
pub const GPIO_O_TYPE_SYNC_DIFF: u8 = 0x70;
pub const GPIO_O_TYPE_PWM_OUT: u8 = 0xE0;
pub const GPIO_O_TYPE_DIRECT: u8 = 0xF0;

pub const MOD_BUFFER_SAMPLES: usize = 65536;
pub const PWE_TABLE_SIZE: usize = 256;
