name: ci-image

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  image:
    name: image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-rust
        with:
          workspaces: xtask
      - run: cargo xtask appliance image lint
      - run: cargo xtask appliance server cross
