name: ci-license

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  license:
    name: license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-rust
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.19.9
      - run: cargo xtask license check
