name: ci-license

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  license:
    name: license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-rust
      - uses: taiki-e/install-action@v2.86.5
        with:
          tool: cargo-deny
      - run: cargo xtask license check
