name: ci-py

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  py:
    name: py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-rust
        with:
          components: rustfmt, clippy
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev cmake
      - uses: astral-sh/setup-uv@v6
      - run: cargo xtask py format
      - run: cargo xtask py lint
      - run: cargo xtask py test --soem
