name: ci-rust

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  rust:
    name: rust (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-rust
        with:
          components: rustfmt, clippy
      - name: Install pcap
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev
      - name: Format
        if: runner.os == 'Linux'
        run: cargo xtask rust format
      - run: cargo xtask rust lint
      - run: cargo xtask rust test
