name: ci-simulator

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  simulator:
    name: simulator (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-rust
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
          workspaces: |
            simulator
            simulator/frontend
            xtask
      - name: Format
        if: runner.os == 'Linux'
        run: cargo xtask simulator format
      - run: cargo xtask simulator lint
      - name: Install cargo-binstall and cargo-about
        if: runner.os == 'Linux'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-about
      - name: Install dioxus-cli
        if: runner.os == 'Linux'
        run: cargo binstall -y dioxus-cli --locked
      - name: Build
        if: runner.os == 'Linux'
        run: cargo xtask simulator build --debug
