name: release-py

on:
  push:
    tags:
      - 'v*'
      - 'py-v*'

defaults:
  run:
    shell: bash

env:
  BEFORE_SCRIPT_LINUX: dnf install -y libpcap-devel cmake clang

jobs:
  build:
    name: wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-rust
      - uses: actions/setup-python@v7
        with:
          python-version: |
            3.12
            3.13
            3.14
      - uses: taiki-e/install-action@v2.85.5
        with:
          tool: cargo-about
      - name: Generate third-party licenses
        run: cargo xtask license generate python

      - name: Build autd3-core
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-core/Cargo.toml --find-interpreter -o dist
      - name: Build autd3
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-pattern
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-pattern/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-pattern-holo
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-pattern-holo/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-modulation
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-modulation/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-link-echocat
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-link-echocat/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-link-ethercrab
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-link-ethercrab/Cargo.toml --find-interpreter -o dist --auditwheel warn
      - name: Build autd3-link-remote
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-link-remote/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-link-twincat
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-link-twincat/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-link-nop
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-link-nop/Cargo.toml --find-interpreter -o dist
      - name: Build autd3-link-soem
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings/python
          manylinux: '2_28'
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          args: --release -m autd3-link-soem/Cargo.toml --find-interpreter -o dist --auditwheel warn

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: bindings/python/dist/*.whl

  publish:
    name: release-py
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
