name: release-crates

on:
  push:
    tags:
      - 'v*'
      - 'rust-v*'

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: release-crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-rust
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev cmake
      - name: Verify the packages assemble
        run: cargo package --workspace --no-verify
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish workspace to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish --workspace --no-verify
      - name: Publish autd3-rs-emulator to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish -p autd3-rs-emulator --manifest-path emulator/Cargo.toml --no-verify
